apiVersion: v1
kind: Pod
metadata:
  name: nexus-pod
  namespace: build
  labels:
    app: nexus
spec:
  containers:
    - name: nexus-container
      image: sonatype/nexus3:latest
      ports:
        - containerPort: 8081